/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedSlaMideaRouteImport } from './routes/_authenticated/sla-midea'
import { Route as AuthenticatedSlaBoschRouteImport } from './routes/_authenticated/sla-bosch'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlaMideaRoute = AuthenticatedSlaMideaRouteImport.update({
  id: '/sla-midea',
  path: '/sla-midea',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlaBoschRoute = AuthenticatedSlaBoschRouteImport.update({
  id: '/sla-bosch',
  path: '/sla-bosch',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/sla-midea': typeof AuthenticatedSlaMideaRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/sla-midea': typeof AuthenticatedSlaMideaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/_authenticated/sla-midea': typeof AuthenticatedSlaMideaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/cadastro' | '/sla-bosch' | '/sla-midea'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/cadastro' | '/sla-bosch' | '/sla-midea'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cadastro'
    | '/_authenticated/sla-bosch'
    | '/_authenticated/sla-midea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sla-midea': {
      id: '/_authenticated/sla-midea'
      path: '/sla-midea'
      fullPath: '/sla-midea'
      preLoaderRoute: typeof AuthenticatedSlaMideaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sla-bosch': {
      id: '/_authenticated/sla-bosch'
      path: '/sla-bosch'
      fullPath: '/sla-bosch'
      preLoaderRoute: typeof AuthenticatedSlaBoschRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedSlaBoschRoute: typeof AuthenticatedSlaBoschRoute
  AuthenticatedSlaMideaRoute: typeof AuthenticatedSlaMideaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadastroRoute: AuthenticatedCadastroRoute,
  AuthenticatedSlaBoschRoute: AuthenticatedSlaBoschRoute,
  AuthenticatedSlaMideaRoute: AuthenticatedSlaMideaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
