/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSlaMideaRouteImport } from './routes/_authenticated/sla-midea'
import { Route as AuthenticatedSlaBoschRouteImport } from './routes/_authenticated/sla-bosch'
import { Route as AuthenticatedPlanoAcaoRouteImport } from './routes/_authenticated/plano-acao'
import { Route as AuthenticatedMelhoriasRouteImport } from './routes/_authenticated/melhorias'
import { Route as AuthenticatedGerenciamentoOperacionalRouteImport } from './routes/_authenticated/gerenciamento-operacional'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedCadastroOportunidadesRouteImport } from './routes/_authenticated/cadastro-oportunidades'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlaMideaRoute = AuthenticatedSlaMideaRouteImport.update({
  id: '/sla-midea',
  path: '/sla-midea',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlaBoschRoute = AuthenticatedSlaBoschRouteImport.update({
  id: '/sla-bosch',
  path: '/sla-bosch',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanoAcaoRoute = AuthenticatedPlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMelhoriasRoute = AuthenticatedMelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGerenciamentoOperacionalRoute =
  AuthenticatedGerenciamentoOperacionalRouteImport.update({
    id: '/gerenciamento-operacional',
    path: '/gerenciamento-operacional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroOportunidadesRoute =
  AuthenticatedCadastroOportunidadesRouteImport.update({
    id: '/cadastro-oportunidades',
    path: '/cadastro-oportunidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/cadastro-oportunidades': typeof AuthenticatedCadastroOportunidadesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/gerenciamento-operacional': typeof AuthenticatedGerenciamentoOperacionalRoute
  '/melhorias': typeof AuthenticatedMelhoriasRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/sla-midea': typeof AuthenticatedSlaMideaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/cadastro-oportunidades': typeof AuthenticatedCadastroOportunidadesRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/gerenciamento-operacional': typeof AuthenticatedGerenciamentoOperacionalRoute
  '/melhorias': typeof AuthenticatedMelhoriasRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/sla-midea': typeof AuthenticatedSlaMideaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/cadastro-oportunidades': typeof AuthenticatedCadastroOportunidadesRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/gerenciamento-operacional': typeof AuthenticatedGerenciamentoOperacionalRoute
  '/_authenticated/melhorias': typeof AuthenticatedMelhoriasRoute
  '/_authenticated/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/_authenticated/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/_authenticated/sla-midea': typeof AuthenticatedSlaMideaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cadastro'
    | '/cadastro-oportunidades'
    | '/diagnostico'
    | '/gerenciamento-operacional'
    | '/melhorias'
    | '/plano-acao'
    | '/sla-bosch'
    | '/sla-midea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cadastro'
    | '/cadastro-oportunidades'
    | '/diagnostico'
    | '/gerenciamento-operacional'
    | '/melhorias'
    | '/plano-acao'
    | '/sla-bosch'
    | '/sla-midea'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cadastro'
    | '/_authenticated/cadastro-oportunidades'
    | '/_authenticated/diagnostico'
    | '/_authenticated/gerenciamento-operacional'
    | '/_authenticated/melhorias'
    | '/_authenticated/plano-acao'
    | '/_authenticated/sla-bosch'
    | '/_authenticated/sla-midea'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sla-midea': {
      id: '/_authenticated/sla-midea'
      path: '/sla-midea'
      fullPath: '/sla-midea'
      preLoaderRoute: typeof AuthenticatedSlaMideaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sla-bosch': {
      id: '/_authenticated/sla-bosch'
      path: '/sla-bosch'
      fullPath: '/sla-bosch'
      preLoaderRoute: typeof AuthenticatedSlaBoschRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plano-acao': {
      id: '/_authenticated/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof AuthenticatedPlanoAcaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/melhorias': {
      id: '/_authenticated/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof AuthenticatedMelhoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerenciamento-operacional': {
      id: '/_authenticated/gerenciamento-operacional'
      path: '/gerenciamento-operacional'
      fullPath: '/gerenciamento-operacional'
      preLoaderRoute: typeof AuthenticatedGerenciamentoOperacionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro-oportunidades': {
      id: '/_authenticated/cadastro-oportunidades'
      path: '/cadastro-oportunidades'
      fullPath: '/cadastro-oportunidades'
      preLoaderRoute: typeof AuthenticatedCadastroOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedCadastroOportunidadesRoute: typeof AuthenticatedCadastroOportunidadesRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedGerenciamentoOperacionalRoute: typeof AuthenticatedGerenciamentoOperacionalRoute
  AuthenticatedMelhoriasRoute: typeof AuthenticatedMelhoriasRoute
  AuthenticatedPlanoAcaoRoute: typeof AuthenticatedPlanoAcaoRoute
  AuthenticatedSlaBoschRoute: typeof AuthenticatedSlaBoschRoute
  AuthenticatedSlaMideaRoute: typeof AuthenticatedSlaMideaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadastroRoute: AuthenticatedCadastroRoute,
  AuthenticatedCadastroOportunidadesRoute:
    AuthenticatedCadastroOportunidadesRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedGerenciamentoOperacionalRoute:
    AuthenticatedGerenciamentoOperacionalRoute,
  AuthenticatedMelhoriasRoute: AuthenticatedMelhoriasRoute,
  AuthenticatedPlanoAcaoRoute: AuthenticatedPlanoAcaoRoute,
  AuthenticatedSlaBoschRoute: AuthenticatedSlaBoschRoute,
  AuthenticatedSlaMideaRoute: AuthenticatedSlaMideaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
