/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardGestaoRouteImport } from './routes/_authenticated/dashboard-gestao'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedGerenciamentoOperacionalRouteImport } from './routes/_authenticated/gerenciamento-operacional'
import { Route as AuthenticatedPlanoAcaoRouteImport } from './routes/_authenticated/plano-acao'
import { Route as AuthenticatedMelhoriasRouteImport } from './routes/_authenticated/melhorias'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedCadastroOportunidadesRouteImport } from './routes/_authenticated/cadastro-oportunidades'
import { Route as AuthenticatedSlaMideaRouteImport } from './routes/_authenticated/sla-midea'
import { Route as AuthenticatedSlaBoschRouteImport } from './routes/_authenticated/sla-bosch'
// ── new routes ──
import { Route as AuthenticatedProdutividadeRouteImport } from './routes/_authenticated/produtividade'
import { Route as AuthenticatedNaoConformidadesRouteImport } from './routes/_authenticated/nao-conformidades'
import { Route as AuthenticatedCustoOperacionalRouteImport } from './routes/_authenticated/custo-operacional'
import { Route as AuthenticatedCheckinOpRouteImport } from './routes/_authenticated/checkin-operacional'
import { Route as AuthenticatedMinhaSemanaRouteImport } from './routes/_authenticated/minha-semana'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedRevisaoSemanalRouteImport } from './routes/_authenticated/revisao-semanal'
import { Route as AuthenticatedCheckinGerencialRouteImport } from './routes/_authenticated/checkin-gerencial'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'

const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)

function mkAuth(id: string, path: string, imp: any) {
  return imp.update({ id, path, getParentRoute: () => AuthenticatedRoute } as any)
}

const AuthenticatedIndexRoute              = mkAuth('/',                       '/',                       AuthenticatedIndexRouteImport)
const AuthenticatedDashboardGestaoRoute    = mkAuth('/dashboard-gestao',       '/dashboard-gestao',       AuthenticatedDashboardGestaoRouteImport)
const AuthenticatedCadastroRoute           = mkAuth('/cadastro',               '/cadastro',               AuthenticatedCadastroRouteImport)
const AuthenticatedGerenciamentoRoute      = mkAuth('/gerenciamento-operacional','/gerenciamento-operacional',AuthenticatedGerenciamentoOperacionalRouteImport)
const AuthenticatedPlanoAcaoRoute          = mkAuth('/plano-acao',             '/plano-acao',             AuthenticatedPlanoAcaoRouteImport)
const AuthenticatedMelhoriasRoute          = mkAuth('/melhorias',              '/melhorias',              AuthenticatedMelhoriasRouteImport)
const AuthenticatedDiagnosticoRoute        = mkAuth('/diagnostico',            '/diagnostico',            AuthenticatedDiagnosticoRouteImport)
const AuthenticatedCadastroOpRoute         = mkAuth('/cadastro-oportunidades', '/cadastro-oportunidades', AuthenticatedCadastroOportunidadesRouteImport)
const AuthenticatedSlaMideaRoute           = mkAuth('/sla-midea',              '/sla-midea',              AuthenticatedSlaMideaRouteImport)
const AuthenticatedSlaBoschRoute           = mkAuth('/sla-bosch',              '/sla-bosch',              AuthenticatedSlaBoschRouteImport)
const AuthenticatedProdutividadeRoute      = mkAuth('/produtividade',          '/produtividade',          AuthenticatedProdutividadeRouteImport)
const AuthenticatedNaoConformidadesRoute   = mkAuth('/nao-conformidades',      '/nao-conformidades',      AuthenticatedNaoConformidadesRouteImport)
const AuthenticatedCustoOperacionalRoute   = mkAuth('/custo-operacional',      '/custo-operacional',      AuthenticatedCustoOperacionalRouteImport)
const AuthenticatedCheckinOpRoute          = mkAuth('/checkin-operacional',    '/checkin-operacional',    AuthenticatedCheckinOpRouteImport)
const AuthenticatedMinhaSemanaRoute        = mkAuth('/minha-semana',           '/minha-semana',           AuthenticatedMinhaSemanaRouteImport)
const AuthenticatedAtividadesRoute         = mkAuth('/atividades',             '/atividades',             AuthenticatedAtividadesRouteImport)
const AuthenticatedMetasRoute              = mkAuth('/metas',                  '/metas',                  AuthenticatedMetasRouteImport)
const AuthenticatedRevisaoSemanalRoute     = mkAuth('/revisao-semanal',        '/revisao-semanal',        AuthenticatedRevisaoSemanalRouteImport)
const AuthenticatedCheckinGerencialRoute   = mkAuth('/checkin-gerencial',      '/checkin-gerencial',      AuthenticatedCheckinGerencialRouteImport)
const AuthenticatedEquipesRoute            = mkAuth('/equipes',                '/equipes',                AuthenticatedEquipesRouteImport)
import { Route as AuthenticatedBancoHorasRouteImport } from './routes/_authenticated/banco-horas'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedPdiRouteImport } from './routes/_authenticated/pdi'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const AuthenticatedBancoHorasRoute       = mkAuth('/banco-horas',              '/banco-horas',            AuthenticatedBancoHorasRouteImport)
const AuthenticatedProjetosRoute         = mkAuth('/projetos',                 '/projetos',               AuthenticatedProjetosRouteImport)
const AuthenticatedPdiRoute              = mkAuth('/pdi',                      '/pdi',                    AuthenticatedPdiRouteImport)
const AuthenticatedRelatoriosRoute       = mkAuth('/relatorios',               '/relatorios',             AuthenticatedRelatoriosRouteImport)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardGestaoRoute: typeof AuthenticatedDashboardGestaoRoute
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedGerenciamentoRoute: typeof AuthenticatedGerenciamentoRoute
  AuthenticatedPlanoAcaoRoute: typeof AuthenticatedPlanoAcaoRoute
  AuthenticatedMelhoriasRoute: typeof AuthenticatedMelhoriasRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedCadastroOpRoute: typeof AuthenticatedCadastroOpRoute
  AuthenticatedSlaMideaRoute: typeof AuthenticatedSlaMideaRoute
  AuthenticatedSlaBoschRoute: typeof AuthenticatedSlaBoschRoute
  AuthenticatedProdutividadeRoute: typeof AuthenticatedProdutividadeRoute
  AuthenticatedNaoConformidadesRoute: typeof AuthenticatedNaoConformidadesRoute
  AuthenticatedCustoOperacionalRoute: typeof AuthenticatedCustoOperacionalRoute
  AuthenticatedCheckinOpRoute: typeof AuthenticatedCheckinOpRoute
  AuthenticatedMinhaSemanaRoute: typeof AuthenticatedMinhaSemanaRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedRevisaoSemanalRoute: typeof AuthenticatedRevisaoSemanalRoute
  AuthenticatedCheckinGerencialRoute: typeof AuthenticatedCheckinGerencialRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedBancoHorasRoute: typeof AuthenticatedBancoHorasRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedPdiRoute: typeof AuthenticatedPdiRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedDashboardGestaoRoute,
  AuthenticatedCadastroRoute,
  AuthenticatedGerenciamentoRoute,
  AuthenticatedPlanoAcaoRoute,
  AuthenticatedMelhoriasRoute,
  AuthenticatedDiagnosticoRoute,
  AuthenticatedCadastroOpRoute,
  AuthenticatedSlaMideaRoute,
  AuthenticatedSlaBoschRoute,
  AuthenticatedProdutividadeRoute,
  AuthenticatedNaoConformidadesRoute,
  AuthenticatedCustoOperacionalRoute,
  AuthenticatedCheckinOpRoute,
  AuthenticatedMinhaSemanaRoute,
  AuthenticatedAtividadesRoute,
  AuthenticatedMetasRoute,
  AuthenticatedRevisaoSemanalRoute,
  AuthenticatedCheckinGerencialRoute,
  AuthenticatedEquipesRoute,
  AuthenticatedFuncionariosRoute,
  AuthenticatedBancoHorasRoute,
  AuthenticatedProjetosRoute,
  AuthenticatedPdiRoute,
  AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard-gestao': typeof AuthenticatedDashboardGestaoRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/gerenciamento-operacional': typeof AuthenticatedGerenciamentoRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/melhorias': typeof AuthenticatedMelhoriasRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/cadastro-oportunidades': typeof AuthenticatedCadastroOpRoute
  '/sla-midea': typeof AuthenticatedSlaMideaRoute
  '/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/nao-conformidades': typeof AuthenticatedNaoConformidadesRoute
  '/custo-operacional': typeof AuthenticatedCustoOperacionalRoute
  '/checkin-operacional': typeof AuthenticatedCheckinOpRoute
  '/minha-semana': typeof AuthenticatedMinhaSemanaRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/revisao-semanal': typeof AuthenticatedRevisaoSemanalRoute
  '/checkin-gerencial': typeof AuthenticatedCheckinGerencialRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/banco-horas': typeof AuthenticatedBancoHorasRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/pdi': typeof AuthenticatedPdiRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}

export interface FileRoutesByTo extends FileRoutesByFullPath {}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard-gestao': typeof AuthenticatedDashboardGestaoRoute
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/gerenciamento-operacional': typeof AuthenticatedGerenciamentoRoute
  '/_authenticated/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/_authenticated/melhorias': typeof AuthenticatedMelhoriasRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/cadastro-oportunidades': typeof AuthenticatedCadastroOpRoute
  '/_authenticated/sla-midea': typeof AuthenticatedSlaMideaRoute
  '/_authenticated/sla-bosch': typeof AuthenticatedSlaBoschRoute
  '/_authenticated/produtividade': typeof AuthenticatedProdutividadeRoute
  '/_authenticated/nao-conformidades': typeof AuthenticatedNaoConformidadesRoute
  '/_authenticated/custo-operacional': typeof AuthenticatedCustoOperacionalRoute
  '/_authenticated/checkin-operacional': typeof AuthenticatedCheckinOpRoute
  '/_authenticated/minha-semana': typeof AuthenticatedMinhaSemanaRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/revisao-semanal': typeof AuthenticatedRevisaoSemanalRoute
  '/_authenticated/checkin-gerencial': typeof AuthenticatedCheckinGerencialRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/banco-horas': typeof AuthenticatedBancoHorasRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/pdi': typeof AuthenticatedPdiRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
